### ISSUE TITLE
More info on compatibility with WK

### ISSUE THREAD

**Issue by sarim** [gregstein/HD-To-TC#2]
Seems like WK must be in `C:\Program Files\microsoft games\age of empires ii` to be successfully installed. Otherwise WK just hangs without any proper error message. "WololoKingdoms has stopped working"

This should be noted in README.

PS: Thank you very much for creating this tool. I've just lured two of my friends to Voobly from Steam with the appeal of doing it with just 3 click. They were refusing to convert after hearing i had to spend 1hour with TeamViewer in another friend's pc to configure compatibility patch and UP with voobly.

**Comment by gregstein** [comment]
Thank you for the feedback Mr. Sarim. Please note that once you click the 3 buttons in HD To TC, you need to reinstall Wololokingdoms, then Wololo data will be installed automatically in `C:\Program Files\microsoft games\age of empires ii\Voobly Mods\AOC\Data Mods\WololoKingdoms`
So the question here did you resintall wololo kingdoms or not? Because it is likely you have already used compatibility patch that is why you need to re-run wololo kingdoms installer again and preferably as administrator.

Let me know how it goes.

Thank you,

**Comment by sarim** [comment]
Ah no. In that computer no other patch was installed. First HD-to-TC was installed successfully. Then WK was tried from Downloads folder. It didn't work, just hanged. Then `WololoKingdoms 5.7` folder was placed in `C:\Program Files\microsoft games\age of empires ii`. This time WK succeeded.

Notice that WK readme says place WK in Age2HD folder if problem arises, but that is definitely meant for compatibility patch. Compatibility patch installs AoC in steam's Age2HD folder. So i thought as HD-to-TC installs AoC in different path, lets place WK there.

Now this is a sample size of one, so can't get a definitive diagnosis from there. If i manage to try it in other fresh computers, i'll let you know what happens.

**Comment by gregstein** [comment]
release V2.2 Fixes the issue now: https://github.com/gregstein/HD-To-TC/releases
